name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'app/src/main/play/**'
  schedule:
    # Every day at 11:30 UTC because we test the client with real data.
    - cron: '30 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle
      - uses: gradle/actions/wrapper-validation@v4
      - run: echo "$RELEASE_KEYSTORE" | base64 -d > /tmp/keystore.jks
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      - run: ./gradlew build
        env:
          RELEASE_KEYSTORE_ALIAS: ognarviewer
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      - if: always()
        run: rm -f /tmp/keystore.jks || true
      - uses: actions/upload-artifact@v4
        with:
          path: app/build/
          if-no-files-found: error
