name: CI

on:
  push:
  schedule:
    # Every day at 12:30 UTC because we test the client with real data.
    - cron: '30 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
        cache: gradle
    - name: gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@v4
      with:
        name: apks
        path: app/build/outputs/apk/**/*.apk
        if-no-files-found: error
        retention-days: 14
        compression-level: 0 # APKs are already compressed
    - uses: actions/upload-artifact@v4
      with:
        name: reports
        path: app/build/reports/
        if-no-files-found: warn
        retention-days: 14
        compression-level: 9
