name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'app/src/main/play/**'
  schedule:
    # Every day at 11:30 UTC because we test the client with real data.
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - uses: gradle/actions/wrapper-validation@v4

      - run: ./gradlew assembleDebug check

      - if: success() && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "$RELEASE_KEYSTORE" | base64 -d > /tmp/keystore.jks
          ./gradlew assembleRelease bundleRelease
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_ALIAS: ognarviewer
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - if: always()
        run: rm -f /tmp/keystore.jks

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          path: |
            app/build/outputs/
            app/build/reports/
          if-no-files-found: error
